### ISSUE TITLE
Flags

### ISSUE THREAD

**Issue by jaikishantulswani** [devploit/nomore403#30]
@devploit Needed some functionality like -r for redirect (optional) and also an argument to avoid the host if it throws 429 Status code

**Comment by devploit** [comment]
Hey, I'll keep an eye on it to implement it soon. Thanks for the feedback.

**Comment by jaikishantulswani** [comment]
@devploit one more thing to filter with status codes like argument 
`
-r for redirect
-er to avoice the target if it throw 429
-mc 200,401 (to select multiple status code to filter)
`

**Comment by devploit** [comment]
Hey, I just upload a new version with -r for redirect and --rate-limit/-l to halt if a 429 (rate-limit ban) is detected. I will keep an eye on the others features for a future version.

**Comment by devploit** [comment]
@jaikishantulswani You have --timeout flag added and i/o timeout messages supressed in the last version.

**Comment by jaikishantulswani** [comment]
@devploit Thank you for the implement. It works well except the i/o timeout messages which are still visible.

**Comment by jaikishantulswani** [comment]
Hi @devploit it would be much more cleaner if it have functionality like:
- Stop at first valid match based on status code and content length
- flags like -mc for match status to filter the desired result like -mc 200
- uniq to get only uniq results based on status code and content-length

**Comment by devploit** [comment]
Solved by yourself https://github.com/devploit/nomore403/pull/39. Thanks man!
