### ISSUE TITLE
Regarding the issue of release versions

### ISSUE THREAD

**Issue by clingerxiangdingdang** [devploit/nomore403#32]
ZH-CN：releases包里不放payloads，那你干嘛还打包？你的releases里文件大小居然有8M？到底放了啥？
EN-US：Why are you still packing the packages when there are no payloads in the releases package? Is the file size in your releases surprisingly 8M? What exactly did it put?

**Comment by devploit** [comment]
Hi, to use the default payloads you need to download the repository and put the release binary in the same folder. The binaries are created by https://github.com/devploit/nomore403/blob/main/.goreleaser.yaml not manually by me.

**Comment by clingerxiangdingdang** [comment]
Thank you very much. We have successfully bypassed it
