### ISSUE TITLE
Use with sqlmap?

### ISSUE THREAD

**Issue by Kali95739** [devploit/nomore403#41]
Can show example or command as one liner

**Comment by devploit** [comment]
Hi @Kali95739,

Using a tool that makes a large number of connections to bypass 403 errors in combination with **sqlmap** is not recommended. The primary reason is that the number of requests required to successfully complete the SQL injection process would grow exponentially, leading to potential performance issues and increasing the likelihood of triggering security mechanisms on the target server.

Instead, the most effective approach is to first identify a bypass method using **nomore403**. Once you've successfully bypassed the 403 restrictions, you can then configure **sqlmap** with the necessary headers or parameters. This targeted strategy minimizes the number of requests needed, making the SQL injection testing process more efficient and less likely to be detected or blocked by the server.

Suppose you've identified that adding a specific header allows you to bypass the 403 error. You can include this header in your sqlmap command as follows:
`sqlmap -u "http://example.com/vulnerable.php?id=1" --headers="X-Forwarded-For: 127.0.0.1" --batch --level=5 --risk=3`
