### ISSUE TITLE
Look for `payloads` folder relative to the executable rather than relative to the current directory

### ISSUE THREAD

**Issue by 0risc** [devploit/nomore403#45]
The `--help` message states:

```
  -f, --folder string         Specify the folder location for payloads if not in the same directory as the executable.
```

but that doesn't seem to actually be true. `nomore403` seems to currently look for payloads relative to the current directory, rather than relative to the executable.

For example
```
git clone https://github.com/devploit/nomore403
cd nomore403
go get
go build
./nomore403 -u http://localhost:8000
```
works

But once I do
```
cd ..
./nomore403/nomore403 --verbose -u http://localhost:8000
```
then I get the error `2024/12/11 21:49:37 Error reading /httpmethods file: open payloads/httpmethods: no such file or directory`

**Comment by devploit** [comment]
Is the intended way of work. If you want to launch nomore403 from a different folder, you can specify the payloads folder with `-f` flag.
